name: Daily Commit Automation

on:
  schedule:
    - cron: "0 3 * * *"  # Runs daily at 03:00 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "22f3001301@ds.study.iitm.ac.in"

      - name: Add a Daily Commit (22f3001301@ds.study.iitm.ac.in)
        run: |
          echo "Daily commit on $(date)" >> daily_update.txt
          git add daily_update.txt
          git commit -m "Automated daily commit $(date)" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/RitushreeM/dev.git main
